---
title: "¢Change"
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  sprints:
    title: Sprints
    output: true
  uploads:
    title: Uploads
    output: true
url: "/project/"
section: COMP 523.602
sass:
  style: compressed
